### ISSUE TITLE
Standard installation on clean Ubuntu 20.04 OS fails with error

### ISSUE THREAD

**Issue by PMBNL** [e-m-b-a/emba#686]
**Describe the bug**
Default installation failes on clean install Remnux OS (Ubuntu 20.04).

**To Reproduce**

1. Clean Remnux OS install (Ubuntu 20.04)
2. Execute Remnux upgrade command
3. Use standard installation with:
-  git clone https://github.com/e-m-b-a/emba.git
-  cd emba
- sudo ./installer.sh -d
4. Installation not succesful with error as shown below:

"------------------------------------------------------------------------------------------------
Error detected - status code 1
Command:  docker-compose up --no-start
Location:  ./installer/I05_emba_docker_image_dl.sh, line 55
Stack Trace:
    [1] I05_emba_docker_image_dl(): ./installer/I05_emba_docker_image_dl.sh, line 55 -> I05_emba_docker_image_dl
    [2] main(): ./installer.sh, line 292 -> main -d

Important: Consider filling out a bug report at https://github.com/e-m-b-a/emba/issues"

**Expected behavior**
An working installation with no errors ;-)

**Screenshots**
Below the complete install logging on screen

**Desktop (please complete the following information):**
- OS: Ubuntu 20.04.4 LTS (Remnux clean install)
- current master branch
- Installation method: default with up to date docker image

**Priority issue**
Are you already a [Sponsor]? - [N]

**Additional context**
Below the installation logging on screen and details about OS used.

remnux@remnux:~/Downloads/emba$ sudo ./installer.sh -d

EMBA - Embedded Linux Analyzer Installer
=================================================================

==> Imported 26 installer module files

Install all dependecies for EMBA in default/docker mode

WARNING: compatibility of distribution/version unknown!
If you know what you are doing you can press any key to continue ...
Created external directory: ./external

Update package lists.
Hit:1 http://packages.microsoft.com/repos/vscode stable InRelease
Get:2 http://ppa.launchpad.net/gift/stable/ubuntu focal InRelease [18.0 kB]                        
Hit:3 https://download.docker.com/linux/ubuntu focal InRelease                                     
Hit:4 https://download.sysdig.com/stable/deb stable-amd64/ InRelease                               
Get:5 https://repo.saltproject.io/py3/ubuntu/20.04/amd64/3004 focal InRelease [2,125 B]            
Hit:6 http://ppa.launchpad.net/openjdk-r/ppa/ubuntu focal InRelease                                
Get:7 http://ppa.launchpad.net/remnux/stable/ubuntu focal InRelease [18.1 kB]                      
Hit:8 https://download.mono-project.com/repo/ubuntu stable-focal InRelease                         
Hit:9 http://ppa.launchpad.net/sift/stable/ubuntu focal InRelease                                  
Hit:10 http://ppa.launchpad.net/wireshark-dev/stable/ubuntu focal InRelease                        
Hit:11 https://packages.microsoft.com/ubuntu/20.04/prod focal InRelease                            
Get:12 http://security.ubuntu.com/ubuntu focal-security InRelease [114 kB]                         
Hit:13 http://us.archive.ubuntu.com/ubuntu focal InRelease                                         
Get:14 http://us.archive.ubuntu.com/ubuntu focal-updates InRelease [114 kB]     
Hit:15 http://deb.nodesource.com/node_14.x focal InRelease                                  
Get:16 http://us.archive.ubuntu.com/ubuntu focal-backports InRelease [108 kB]
Hit:17 http://www.inetsim.org/debian binary/ InRelease
Fetched 374 kB in 1s (318 kB/s)
Reading package lists... Done

[+] I01_default_apps_host
=================================================================

To use EMBA, some applications must be installed and some data (database for CVS for example) downloaded and parsed.

These applications will be installed/updated:

jq
Description: lightweight and flexible command-line JSON processor
Download-Size: 50.2 kB
jq won't be updated.

shellcheck
Description: lint tool for shell scripts
Download-Size: 2,303 kB
shellcheck will be newly installed.

unzip
Description: De-archiver for .zip files
Download-Size: 168 kB
unzip won't be updated.

docker-compose
Description: Punctual, lightweight development environments using Docker
Download-Size: 92.7 kB
docker-compose won't be updated.

bc
Description: GNU bc arbitrary precision calculator language
Download-Size: 86.3 kB
bc will be newly installed.

coreutils
Description: GNU core utilities
Download-Size: 1,249 kB
coreutils won't be updated.

ncurses-bin
Description: terminal-related programs and man pages
Download-Size: 172 kB
ncurses-bin won't be updated.

libnotify-bin
Description: sends desktop notifications to a notification daemon (Utilities)
Download-Size: 7,288 B
libnotify-bin will be newly installed.

inotify-tools
Description: command-line programs providing a simple interface to inotify
Download-Size: 22.8 kB
inotify-tools will be newly installed.

git
Description: fast, scalable, distributed revision control system
Download-Size: 4,605 kB
git won't be updated.

net-tools
Description: NET-3 networking toolkit
Download-Size: 196 kB
net-tools won't be updated.

curl
Description: command line tool for transferring data with URL syntax
Download-Size: 161 kB
curl won't be updated.

python3-pip
Description: Python package installer
Download-Size: 231 kB
python3-pip won't be updated.

requests
Description: Python HTTP for Humans. / Version: NA
requests is already installed and will be updated (if a newer version is available).

These applications will be installed/updated!

Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  libinotifytools0
The following NEW packages will be installed:
  bc inotify-tools libinotifytools0 libnotify-bin shellcheck
0 upgraded, 5 newly installed, 0 to remove and 393 not upgraded.
Need to get 2,437 kB of archives.
After this operation, 18.0 MB of additional disk space will be used.
Get:1 http://us.archive.ubuntu.com/ubuntu focal/main amd64 bc amd64 1.07.1-2build1 [86.3 kB]
Get:2 http://us.archive.ubuntu.com/ubuntu focal/universe amd64 libinotifytools0 amd64 3.14-8 [17.8 kB]
Get:3 http://us.archive.ubuntu.com/ubuntu focal/universe amd64 inotify-tools amd64 3.14-8 [22.8 kB]
Get:4 http://us.archive.ubuntu.com/ubuntu focal-updates/main amd64 libnotify-bin amd64 0.7.9-1ubuntu3.20.04.2 [7,288 B]
Get:5 http://us.archive.ubuntu.com/ubuntu focal/universe amd64 shellcheck amd64 0.7.0-2build2 [2,303 kB]
Fetched 2,437 kB in 1s (2,563 kB/s)   
Selecting previously unselected package bc.
(Reading database ... 208064 files and directories currently installed.)
Preparing to unpack .../bc_1.07.1-2build1_amd64.deb ...
Unpacking bc (1.07.1-2build1) ...
Selecting previously unselected package libinotifytools0:amd64.
Preparing to unpack .../libinotifytools0_3.14-8_amd64.deb ...
Unpacking libinotifytools0:amd64 (3.14-8) ...
Selecting previously unselected package inotify-tools.
Preparing to unpack .../inotify-tools_3.14-8_amd64.deb ...
Unpacking inotify-tools (3.14-8) ...
Selecting previously unselected package libnotify-bin.
Preparing to unpack .../libnotify-bin_0.7.9-1ubuntu3.20.04.2_amd64.deb ...
Unpacking libnotify-bin (0.7.9-1ubuntu3.20.04.2) ...
Selecting previously unselected package shellcheck.
Preparing to unpack .../shellcheck_0.7.0-2build2_amd64.deb ...
Unpacking shellcheck (0.7.0-2build2) ...
Setting up libinotifytools0:amd64 (3.14-8) ...
Setting up bc (1.07.1-2build1) ...
Setting up shellcheck (0.7.0-2build2) ...
Setting up libnotify-bin (0.7.9-1ubuntu3.20.04.2) ...
Setting up inotify-tools (3.14-8) ...
Processing triggers for libc-bin (2.31-0ubuntu9.9) ...
Processing triggers for man-db (2.9.1-1) ...
Processing triggers for install-info (6.7.0.dfsg.2-5) ...
Requirement already satisfied: requests in /usr/local/lib/python3.8/dist-packages (2.31.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.8/dist-packages (from requests) (3.4)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.8/dist-packages (from requests) (2.1.1)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.8/dist-packages (from requests) (2.0.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.8/dist-packages (from requests) (2023.5.7)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

[+] I01_default_apps
=================================================================

[+] I13_disasm
=================================================================

[+] I05_emba_docker_image_dl
=================================================================

docker.io
Description: Linux container runtime
Download-Size: 30.3 MB
docker.io won't be updated.

embeddedanalyzer/emba docker image
Description: EMBA docker images used for firmware analysis.
Download-Size : 4928 MB

docker.io and the EMBA docker image (if not already on the system) will be downloaded and installed!
Reading package lists... Done
Building dependency tree       
Reading state information... Done
0 upgraded, 0 newly installed, 0 to remove and 393 not upgraded.
18890
EMBA docker image will be downloaded.
CONTAINER VARIABLE SET TO embeddedanalyzer/emba
Using default tag: latest
latest: Pulling from embeddedanalyzer/emba
b7265b2b6487: Pull complete 
e079124eb063: Pull complete 
9d8a2209dfb0: Pull complete 
88baef64e930: Pull complete 
4f95762e7e49: Pull complete 
bcceb17f6da3: Pull complete 
c9317181a104: Pull complete 
Digest: sha256:f69ebe7fb0bbd9ff880cded61ae5e91ce109cf83c2c79e324ab03c4e7c929243
Status: Downloaded newer image for embeddedanalyzer/emba:latest
docker.io/embeddedanalyzer/emba:latest
WARNING: The FIRMWARE variable is not set. Defaulting to a blank string.
WARNING: The LOG variable is not set. Defaulting to a blank string.
WARNING: The EMBA variable is not set. Defaulting to a blank string.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/docker/api/client.py", line 214, in _retrieve_server_version
    return self.version(api_version=False)["ApiVersion"]
  File "/usr/local/lib/python3.8/dist-packages/docker/api/daemon.py", line 181, in version
    return self._result(self._get(url), json=True)
  File "/usr/local/lib/python3.8/dist-packages/docker/utils/decorators.py", line 46, in inner
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/docker/api/client.py", line 237, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
  File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 790, in urlopen
    response = self._make_request(
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 496, in _make_request
    conn.request(
TypeError: request() got an unexpected keyword argument 'chunked'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/docker-compose", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/compose/cli/main.py", line 81, in main
    command_func()
  File "/usr/local/lib/python3.8/dist-packages/compose/cli/main.py", line 200, in perform_command
    project = project_from_options('.', options)
  File "/usr/local/lib/python3.8/dist-packages/compose/cli/command.py", line 60, in project_from_options
    return get_project(
  File "/usr/local/lib/python3.8/dist-packages/compose/cli/command.py", line 152, in get_project
    client = get_client(
  File "/usr/local/lib/python3.8/dist-packages/compose/cli/docker_client.py", line 41, in get_client
    client = docker_client(
  File "/usr/local/lib/python3.8/dist-packages/compose/cli/docker_client.py", line 170, in docker_client
    client = APIClient(use_ssh_client=not use_paramiko_ssh, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/docker/api/client.py", line 197, in __init__
    self._version = self._retrieve_server_version()
  File "/usr/local/lib/python3.8/dist-packages/docker/api/client.py", line 221, in _retrieve_server_version
    raise DockerException(
docker.errors.DockerException: Error while fetching server API version: request() got an unexpected keyword argument 'chunked'
------------------------------------------------------------------------------------------------
Error detected - status code 1
Command:  docker-compose up --no-start
Location:  ./installer/I05_emba_docker_image_dl.sh, line 55
Stack Trace:
    [1] I05_emba_docker_image_dl(): ./installer/I05_emba_docker_image_dl.sh, line 55 -> I05_emba_docker_image_dl
    [2] main(): ./installer.sh, line 292 -> main -d

Important: Consider filling out a bug report at https://github.com/e-m-b-a/emba/issues

------------------------------------------------------------------------------------------------
remnux@remnux:~/Downloads/emba$ cat /etc/*-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.4 LTS"
NAME="Ubuntu"
VERSION="20.04.4 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.4 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

**Comment by PMBNL** [comment]
Sorry, I misread the prerequisite. Thanks for response.
